### ISSUE TITLE
Maps 

### ISSUE THREAD

**Issue by danioxoli** [GISdevio/MaTREEd#2]
Creare legenda dinamica x 7 mappe derivanti da attributi diversi dello stesso layer (madrid_neighbours)  -> accendo/spengo strato, uno per volta in visualizzazione, se lo strato viene selezionato la scala di colore si apre in automatico sotto il nome

Titolo Mappa (nome campo)
1. Trees density [trees/Km2] (tot_trees_n)
2. Mean trees trunk perimeter [m] (avg_trunk_girth)
3. Mean trees height [m] (avg_height)
4. Mean trees canopy diameter [m] (avg_crown_diameter)
5. Trees canopy coverage [area %] (tree_cover)
6. CO2 stock [Kg/Km2] (sum_c_stock_n)
7. CO2 sequestration [Kg/y/Km2] (sum_c_stock_n)

**Comment by danioxoli** [comment]
L'idea va bene, correggere come da figura

![Immagine1](https://user-images.githubusercontent.com/15163569/101982721-276a0880-3c76-11eb-825e-5dbe5a8f8c66.png)

**Comment by MarcoMinghini** [comment]
sempre sull'interfaccia, controllare che in 'CO2' il '2' sia messo a pedice

**Comment by GabrielePrestifilippo** [comment]
@danioxoli 

- [x]  aggiungere colori e valori per creare legende

**Comment by danioxoli** [comment]
**1. Trees density [trees/Km2] (tot_trees_n)**

0 - 2161 #f7fcf5
2161 - 3188 #caeac3
3188 - 4656 #7bc87c
4656 - 7156  #2a924a
7156 - 24011 #00441b

**2. Mean trees trunk girth [m] (avg_trunk_girth)**
(Nome mappa cambiato! @GabrielePrestifilippo )
0 - 0.55 #018571
0.55 - 0.625 #80cdc1
0.625 - 0.677 #f5f5f5
0.677 - 0.751 #dfc27d
0.751 - 0.943 #a6611a

**3. Mean trees height [m] (avg_height)**

0 - 6.93 #ffffb2
6.93 - 7.71 #fecc5c
7.71 - 8.41 #fd8d3c
8.41 - 9.18 #f03b20
9.18 - 11.6 #bd0026

**4. Mean trees canopy diameter [m] (avg_crown_diameter)**

0 - 4.02 #edf8fb
4.02 - 4.7 #b3cde3
4.7 - 5.19 #8c96c6
5.19 - 5.61 #8856a7
5.61 - 7.26 #810f7c

**5. Trees canopy coverage [area %] (tree_cover)**

0 - 2.8 #ffffcc
2.8 - 5.8 #c2e699
5.8 - 8.7 #78c679
8.7 - 11.8 #31a354
11.8 - 23.4 #006837

**6. CO2 stock [Kg/Km2] (sum_c_stock_n)**

81 - 9425 #fde725
9425 - 20265 #5dc962
20265 - 32218 #20908d
32218 - 51895 #3a528b
51895 - 243345 #440154

**7. CO2 sequestration [Kg/y/Km2] (sum_c_stock_n)**

14 - 1618 #2b83ba
1618 - 3324 #abdda4
3324 - 5263 #ffffbf
5263 - 8479 #fdae61
8479 - 38781 #d7191c

**Comment by GabrielePrestifilippo** [comment]
qui ci sono i valori da riempire, basta seguire il formato dei due presenti:
https://github.com/GISdevio/MaTREEd/blob/main/webapp/src/static/legends.js

Nella `colorMap` l'ultimo array contiene un solo valore e non una coppia, in quel caso viene scritto nella legenda `0-valore prima`

**Comment by danioxoli** [comment]
![C8AC2ADC-DC31-4382-9C13-20A7C07993CF](https://user-images.githubusercontent.com/15163569/102322233-060f6200-3f7f-11eb-8b8a-af1d1bb74ead.jpeg)

@GabrielePrestifilippo usare nome mappe indicato nel [commento precedente](https://github.com/GISdevio/MaTREEd/issues/2#issuecomment-745551952) (escluso nome campo originale in parentesi)
